name: pumpro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  video_player: ^2.8.2
  youtube_player_flutter: ^8.1.2
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
    