// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGzzvH-Rg6boAi7-t3xUplPgzJfQRE46M',
    appId: '1:578652789229:web:f4090c4ca5e015b29befe4',
    messagingSenderId: '578652789229',
    projectId: 'pumpro-d469b',
    authDomain: 'pumpro-d469b.firebaseapp.com',
    storageBucket: 'pumpro-d469b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGzzvH-Rg6boAi7-t3xUplPgzJfQRE46M',
    appId: '1:578652789229:android:416bcae592002a549befe4',
    messagingSenderId: '578652789229',
    projectId: 'pumpro-d469b',
    storageBucket: 'pumpro-d469b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGzzvH-Rg6boAi7-t3xUplPgzJfQRE46M',
    appId: '1:578652789229:ios:4c00fc0a25efe9249befe4',
    messagingSenderId: '578652789229',
    projectId: 'pumpro-d469b',
    storageBucket: 'pumpro-d469b.firebasestorage.app',
    iosClientId:
        '578652789229-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.example.pumpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGzzvH-Rg6boAi7-t3xUplPgzJfQRE46M',
    appId: '1:578652789229:ios:4c00fc0a25efe9249befe4',
    messagingSenderId: '578652789229',
    projectId: 'pumpro-d469b',
    storageBucket: 'pumpro-d469b.firebasestorage.app',
    iosClientId:
        '578652789229-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.example.pumpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGzzvH-Rg6boAi7-t3xUplPgzJfQRE46M',
    appId: '1:578652789229:web:f4090c4ca5e015b29befe4',
    messagingSenderId: '578652789229',
    projectId: 'pumpro-d469b',
    storageBucket: 'pumpro-d469b.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAGzzvH-Rg6boAi7-t3xUplPgzJfQRE46M',
    appId: '1:578652789229:web:f4090c4ca5e015b29befe4',
    messagingSenderId: '578652789229',
    projectId: 'pumpro-d469b',
    storageBucket: 'pumpro-d469b.firebasestorage.app',
  );
}
